sonar.projectKey=Le-Nid_nid
sonar.organization=le-nid


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=nid
sonar.projectVersion=0.1.1


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=backend/src,frontend/src
sonar.tests=backend/src,frontend/src
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.exclusions=**/*.test.ts,**/*.spec.ts
sonar.typescript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8